# Generated by Django 5.0.6 on 2024-07-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_matrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='response_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
