# Generated by Django 5.0.6 on 2024-07-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_matrix', '0002_chat_message_tokens_chat_response_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='sentiment',
            field=models.TextField(default=''),
        ),
    ]
