# Generated by Django 5.0.6 on 2024-07-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_matrix', '0004_rename_chat_chatsentimentanalysis_chatsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsummary',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
